project_name: gopublic.cli
strict: true
module:
    base_module: gopublic
    instance_cls: "<class 'gopublic.GopublishInstance'>"
    instance_func: GopublishInstance
    instance_args: []
    instance_kwargs:
        url: "http://0.0.0.0:80"

    ignore:
        top_attrs:
            - 'url'
            - 'login'
            - 'endpoints'
            - 'gopublish_version'
            - 'gopublish_mode'
            - '_get_endpoints'
            - '_get_status'
        funcs:
            - get
            - post

documentation: |
    Documentation for gopublic
