project_name: gopublic
strict: true
module:
    base_module: gopublish
    instance_cls: "<class 'gopublish.GopublishInstance'>"
    instance_func: GopublishInstance
    instance_args: []
    instance_kwargs:
        url: "http://0.0.0.0:80"

    ignore:
        top_attrs:
            - 'url'
            - 'login'
            - 'endpoints'
            - 'gopublish_version'
            - 'gopublish_mode'
            - '_get_endpoints'
            - '_get_status'
        funcs:
            - get
            - post

documentation: |
    Bla bla bla
